CREATE DATABASE IF NOT EXISTS poverty;
USE poverty;

DROP TABLE IF EXISTS WB_Regions;
CREATE TABLE IF NOT EXISTS WB_Regions (
WB_REG_ID VARCHAR(10) NOT NULL PRIMARY KEY,
Name VARCHAR(255)
);

DROP TABLE IF EXISTS WB_IncomeLevels;
CREATE TABLE IF NOT EXISTS WB_IncomeLevels (
WB_INCLEVEL_ID VARCHAR(10) NOT NULL PRIMARY KEY,
Name VARCHAR(255)
);

DROP TABLE IF EXISTS WB_Countries;
CREATE TABLE IF NOT EXISTS WB_Countries (
ISO3 VARCHAR(3) NOT NULL PRIMARY KEY,
WB_REG_ID VARCHAR(3),
WB_INCLEVEL_ID VARCHAR(3),
Name VARCHAR(255)
);

DROP TABLE IF EXISTS OECD_Poverty_Gap;
CREATE TABLE IF NOT EXISTS OECD_Poverty_Gap (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value DECIMAL,
Description VARCHAR(255)
);

DROP TABLE IF EXISTS OECD_Poverty_Line;
CREATE TABLE IF NOT EXISTS OECD_Poverty_Line (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value DECIMAL,
Description VARCHAR(255)
);

DROP TABLE IF EXISTS OECD_GDP;
CREATE TABLE IF NOT EXISTS OECD_GDP (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value DECIMAL,
Description VARCHAR(255)
);

DROP TABLE IF EXISTS WB_Population;
CREATE TABLE IF NOT EXISTS WB_Population (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value DECIMAL,
Description VARCHAR(255)
);