
DROP TABLE IF EXISTS WB_Regions;
CREATE TABLE IF NOT EXISTS WB_Regions (
WB_REG_ID VARCHAR(10) NOT NULL PRIMARY KEY,
Name VARCHAR(255)
);

DROP TABLE IF EXISTS Countries;
CREATE TABLE IF NOT EXISTS Countries (
ISO3 VARCHAR(3) NOT NULL PRIMARY KEY,
WB_REG_ID VARCHAR(10),
Name VARCHAR(255),
FOREIGN KEY (WB_REG_ID) REFERENCES WB_Regions(WB_REG_ID)
);

DROP TABLE IF EXISTS Poverty_Gap;
CREATE TABLE IF NOT EXISTS Poverty_Gap (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value FLOAT,
Description VARCHAR(255),
FOREIGN KEY (ISO3) REFERENCES Countries(ISO3)
);

DROP TABLE IF EXISTS Poverty_Line;
CREATE TABLE IF NOT EXISTS Poverty_Line (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value FLOAT,
Description VARCHAR(255),
FOREIGN KEY (ISO3) REFERENCES Countries(ISO3)
);

DROP TABLE IF EXISTS GDP;
CREATE TABLE IF NOT EXISTS GDP (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value FLOAT,
Description VARCHAR(255),
FOREIGN KEY (ISO3) REFERENCES Countries(ISO3)
);

CREATE TABLE IF NOT EXISTS Population (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISO3 VARCHAR(3),
Year INT,
Value FLOAT,
Description VARCHAR(255),
FOREIGN KEY (ISO3) REFERENCES Countries(ISO3)
);